what is classification -->

categorizing a given set of data into classes 

-- can be perform on both structured and unstructured data



In [3]:
import numpy as np
x= np.array([[0,0],[0,1],[1,0],[1,1]])
y= np.array([0,1,1,1])

In [4]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
w = np.array([1,1])

In [6]:
b = -0.5

In [9]:
def activation(z):
    if z >=0:
        return 1
    else:
        return 0

In [10]:
pred =[]
for a in x:
    y_hat = np.dot(a,w) + b
    pred.append(activation(y_hat))

In [11]:
pred

[0, 1, 1, 1]

In [12]:
import math

In [13]:
epochs = 100
alpha= 0.2



In [15]:
import random

In [22]:
w0 =np.random.random()
w1 =np.random.random()
w2 = np.random.random()

In [21]:
del_w0=1
del_w1=1
del_w2=1

In [23]:
train_data_temp=[[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
train_data=np.asarray(train_data_temp)
op =np.array([0,1,1,1,1,1,1,1])

In [24]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [25]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [26]:
y = (x*w) + b

In [28]:
bias =0
for i in range(epochs):
    j=0
    for x in train_data:
        y_hat = (x[0] * w0) + (x[1] * w1) + (x[2] * w2) + bias
        
        if y_hat>=0:
            act =1
        else:
            act =0
        err =op[j] - act
        
        del_w0=alpha*x[0]*err
        del_w1=alpha*x[1]*err
        del_w2=alpha*x[2]*err

        w0 += del_w0
        w1 += del_w1
        w2 += del_w2

        j += 1
        # print("epoch:", i, "sample:", j, "weights:", w0, w1, w2)

print("final weights:", w0, w1, w2)

final weights: 0.48873267188413594 0.1447913409621644 0.3627952094210174


Binary classification 

-- requires two classes , one in normal state and other in aberrant state



logistic Regression